apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-service-config
  namespace: spark-monitor
data:
  DB_HOST:           "postgresql"
  DB_PORT:           "5432"
  DB_NAME:           "spark_monitor_db"
  QUARKUS_HTTP_PORT: "8081"
